version: "3"

vars:
  ENDPOINT_POINT: FOUNDRY_NEXTGEN_ENDPOINT
  INFRA_DIR: infrastructure
  APP_PORT: 8082

tasks:
  default:
    cmds:
      - task --list

  up:
    desc: Creates complete Azure environment for {{.TITLE}}
    cmds:
      - task: _init
      - task: apply
      - task: infra:config

  apply:
    desc: Apply Terraform infrastructure
    cmds:
      - terraform -chdir=./{{.INFRA_DIR}} apply -auto-approve -compact-warnings
        -var "region={{.REGION}}"
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    dir: '{{.INFRA_DIR}}'
    cmds:
      - az group list --tag Application="{{.TITLE}}" --query "[].name" -o tsv | xargs --no-run-if-empty -ot -n 1 az group delete -y --no-wait -n || true
      - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info terraform.tfstate.* || true


  _init:
    internal: true
    cmds:
      - terraform -chdir=./{{.INFRA_DIR}} init -upgrade
      - terraform -chdir=./{{.INFRA_DIR}} workspace new {{.REGION}} || true
      - terraform -chdir=./{{.INFRA_DIR}} workspace select {{.REGION}}
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'